### ISSUE TITLE
download DxyWindow on a HPC

### ISSUE THREAD

**Issue by HomereAMK** [tplinderoth/PopGenomicsTools#1]
Hej Tyler,
I would like to install https://github.com/tplinderoth/PopGenomicsTools on my HPC (mostly to use your DxyWindow). Should i git clone then cd in the DxyWindow folder and do make?
Homère

**Comment by tplinderoth** [comment]
Yep. That should work. That will compile all of the programs. Alternatively, if you only want to use the dxyWindow program you can cd into the PopGenomicsTools directory and type `g++ -O3 -Wall dxyWindow.cpp -o dxyWindow -lz -lboost_iostreams`
